#!/usr/bin/env python3
"""
mkapk — Create an Alpine Linux APK v2 package from a directory of files.

No external dependencies beyond the Python 3 standard library (and optionally
the `openssl` CLI for signing).  Does not require `abuild` or the Alpine SDK.

APK v2 binary format
────────────────────
An APK v2 package is the concatenation of 2 or 3 separate gzip streams:

  [signature gzip stream]  — optional; a tar SEGMENT (no end-of-tar marker)
  [control gzip stream]    — a tar SEGMENT (no end-of-tar marker)
  [data gzip stream]       — a full TARBALL (with end-of-tar marker)

The signature and control layers must be tar "segments": raw tar records
WITHOUT the two 512-byte null blocks that normally terminate a tar archive.
Only the data layer (always last) is a proper tarball.

Each regular file in the data tarball carries a PAX extended header named
APK-TOOLS.checksum.SHA1 containing the hex-encoded SHA1 hash of the file
contents.  This is what Alpine's `abuild-tar --hash` adds.
"""

import argparse
import gzip
import hashlib
import io
import os
import shutil
import stat
import subprocess
import sys
import tarfile
import tempfile
import time


BLOCK = 512
NULLBLOCK = b"\0" * BLOCK

INSTALL_SCRIPTS = (
    ".pre-install",
    ".post-install",
    ".pre-deinstall",
    ".post-deinstall",
    ".pre-upgrade",
    ".post-upgrade",
    ".trigger",
)


# ── tar helpers ──────────────────────────────────────────────────────────────

def _make_tar_bytes(root: str, relpaths: list[str], *,
                    include_hash: bool, include_eof: bool) -> bytes:
    """Build a tar archive in memory.

    Args:
        root:         Filesystem directory that relpaths are relative to.
        relpaths:     Sorted list of relative paths to include.
        include_hash: Embed APK-TOOLS.checksum.SHA1 PAX headers on regular files.
        include_eof:  Keep the end-of-archive marker (True → tarball, False → segment).
    """
    buf = io.BytesIO()
    tf = tarfile.open(fileobj=buf, mode="w", format=tarfile.PAX_FORMAT)

    for relpath in relpaths:
        fullpath = os.path.join(root, relpath)
        info = tf.gettarinfo(name=fullpath, arcname=relpath)
        info.uid = 0
        info.gid = 0
        info.uname = "root"
        info.gname = "root"

        if info.isreg():
            with open(fullpath, "rb") as fh:
                filedata = fh.read()
            if include_hash:
                sha1 = hashlib.sha1(filedata).hexdigest()
                info.pax_headers["APK-TOOLS.checksum.SHA1"] = sha1
            tf.addfile(info, io.BytesIO(filedata))
        else:
            tf.addfile(info)

    tf.close()
    data = buf.getvalue()

    if not include_eof:
        # Strip trailing null blocks (end-of-archive marker + padding).
        end = len(data)
        while end >= BLOCK and data[end - BLOCK : end] == NULLBLOCK:
            end -= BLOCK
        data = data[:end]

    return data


def _gzip_compress(data: bytes) -> bytes:
    """gzip-compress *data* deterministically (no filename, no timestamp)."""
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as gz:
        gz.write(data)
    return buf.getvalue()


# ── file discovery ───────────────────────────────────────────────────────────

def _walk_sorted(root: str) -> list[str]:
    """Return a sorted list of relative paths under *root* (dirs and files)."""
    paths: list[str] = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        rel = os.path.relpath(dirpath, root)
        if rel != ".":
            paths.append(rel)
        for fn in sorted(filenames):
            paths.append(os.path.join(rel, fn) if rel != "." else fn)
    return paths


def _dir_size(path: str) -> int:
    """Return total size in bytes of all files under *path*."""
    total = 0
    for dirpath, _, filenames in os.walk(path):
        for fn in filenames:
            fp = os.path.join(dirpath, fn)
            if not os.path.islink(fp):
                total += os.path.getsize(fp)
    return total


# ── .PKGINFO ────────────────────────────────────────────────────────────────

def _build_pkginfo(*, name: str, version: str, release: str, desc: str,
                   url: str, arch: str, license_: str, maintainer: str,
                   installed_size: int, datahash: str,
                   depends: list[str]) -> str:
    lines = [
        f"# Generated by mkapk",
        f"pkgname = {name}",
        f"pkgver = {version}-{release}",
        f"pkgdesc = {desc}",
        f"url = {url}",
        f"builddate = {int(time.time())}",
        f"packager = mkapk",
        f"size = {installed_size}",
        f"arch = {arch}",
        f"origin = {name}",
        f"maintainer = {maintainer}",
        f"license = {license_}",
        f"datahash = {datahash}",
    ]
    for dep in depends:
        dep = dep.strip()
        if dep:
            lines.append(f"depend = {dep}")
    return "\n".join(lines) + "\n"


# ── signing ──────────────────────────────────────────────────────────────────

def _sign_control(control_gz: bytes, keyfile: str) -> tuple[bytes, str]:
    """Sign *control_gz* with the RSA private key at *keyfile*.

    Returns (signature_gzip_stream, sig_filename).
    Uses the openssl CLI because Python's stdlib doesn't support PKCS#1 v1.5
    RSA-SHA1 signing without third-party packages.
    """
    key_basename = os.path.basename(keyfile)
    if key_basename.endswith(".rsa"):
        key_basename = key_basename[:-4]
    sig_name = f".SIGN.RSA.{key_basename}.pub"

    with tempfile.NamedTemporaryFile() as ctrl_tmp, \
         tempfile.NamedTemporaryFile() as sig_tmp:
        ctrl_tmp.write(control_gz)
        ctrl_tmp.flush()

        subprocess.run(
            ["openssl", "dgst", "-sha1", "-sign", keyfile,
             "-out", sig_tmp.name, ctrl_tmp.name],
            check=True,
        )

        sig_data = open(sig_tmp.name, "rb").read()

    # Build a tar segment containing just the signature file.
    buf = io.BytesIO()
    tf = tarfile.open(fileobj=buf, mode="w", format=tarfile.PAX_FORMAT)
    info = tarfile.TarInfo(name=sig_name)
    info.size = len(sig_data)
    info.mode = 0o644
    info.uid = 0
    info.gid = 0
    info.uname = "root"
    info.gname = "root"
    info.mtime = int(time.time())
    tf.addfile(info, io.BytesIO(sig_data))
    tf.close()

    raw = buf.getvalue()
    end = len(raw)
    while end >= BLOCK and raw[end - BLOCK : end] == NULLBLOCK:
        end -= BLOCK
    raw = raw[:end]

    return _gzip_compress(raw), sig_name


# ── main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    ap = argparse.ArgumentParser(
        prog="mkapk",
        description="Create an Alpine Linux APK v2 package from a directory.",
    )
    ap.add_argument("-n", "--name", required=True, help="Package name")
    ap.add_argument("-v", "--version", required=True, help="Package version (e.g. 1.0.0)")
    ap.add_argument("-d", "--directory", required=True,
                    help="Source directory (mirrors install layout)")
    ap.add_argument("-a", "--arch", default="x86_64", help="Architecture (default: x86_64)")
    ap.add_argument("-r", "--release", default="r0", help="Release / build number (default: r0)")
    ap.add_argument("-D", "--desc", default=None, help="One-line description")
    ap.add_argument("-u", "--url", default="https://localhost", help="Project URL")
    ap.add_argument("-l", "--license", default="MIT", dest="license_",
                    help="License identifier (default: MIT)")
    ap.add_argument("-m", "--maintainer", default="Unknown <unknown@localhost>",
                    help="Maintainer string")
    ap.add_argument("-p", "--depends", default="",
                    help="Comma-separated runtime dependencies")
    ap.add_argument("-o", "--outdir", default=".", help="Output directory (default: .)")
    ap.add_argument("-k", "--key", default=None, help="RSA private key for signing")
    args = ap.parse_args()

    src = os.path.abspath(args.directory)
    if not os.path.isdir(src):
        ap.error(f"source directory '{args.directory}' does not exist")

    desc = args.desc or f"{args.name} package"
    depends = [d.strip() for d in args.depends.split(",") if d.strip()] if args.depends else []
    outdir = os.path.abspath(args.outdir)
    os.makedirs(outdir, exist_ok=True)

    # ── staging ──────────────────────────────────────────────────────────────
    work = tempfile.mkdtemp(prefix="mkapk-")
    try:
        data_dir = os.path.join(work, "data")
        ctrl_dir = os.path.join(work, "control")
        shutil.copytree(src, data_dir, symlinks=True, dirs_exist_ok=True)
        os.makedirs(ctrl_dir, exist_ok=True)

        # Move install scripts from data → control.
        for script in INSTALL_SCRIPTS:
            p = os.path.join(data_dir, script)
            if os.path.isfile(p):
                dest = os.path.join(ctrl_dir, script)
                shutil.move(p, dest)
                os.chmod(dest, 0o755)

        info_msg("Collecting files")

        # ── data tarball ─────────────────────────────────────────────────────
        data_paths = _walk_sorted(data_dir)
        if not data_paths:
            ap.error("source directory is empty (no files to package)")

        data_tar = _make_tar_bytes(data_dir, data_paths,
                                   include_hash=True, include_eof=True)
        data_gz = _gzip_compress(data_tar)

        datahash = hashlib.sha256(data_gz).hexdigest()
        installed_size = _dir_size(data_dir)

        # ── .PKGINFO ────────────────────────────────────────────────────────
        info_msg("Generating .PKGINFO")

        pkginfo = _build_pkginfo(
            name=args.name, version=args.version, release=args.release,
            desc=desc, url=args.url, arch=args.arch, license_=args.license_,
            maintainer=args.maintainer, installed_size=installed_size,
            datahash=datahash, depends=depends,
        )
        pkginfo_path = os.path.join(ctrl_dir, ".PKGINFO")
        with open(pkginfo_path, "w") as f:
            f.write(pkginfo)

        # ── control segment ──────────────────────────────────────────────────
        ctrl_paths = sorted(
            e for e in os.listdir(ctrl_dir)
            if os.path.isfile(os.path.join(ctrl_dir, e))
        )
        ctrl_tar = _make_tar_bytes(ctrl_dir, ctrl_paths,
                                   include_hash=False, include_eof=False)
        ctrl_gz = _gzip_compress(ctrl_tar)

        # ── optional signing ─────────────────────────────────────────────────
        sig_gz = None
        if args.key:
            if not os.path.isfile(args.key):
                ap.error(f"signing key '{args.key}' not found")
            if not shutil.which("openssl"):
                ap.error("openssl is required for signing")
            info_msg(f"Signing with {args.key}")
            sig_gz, _ = _sign_control(ctrl_gz, args.key)

        # ── assemble ─────────────────────────────────────────────────────────
        apk_name = f"{args.name}-{args.version}-{args.release}.apk"
        apk_path = os.path.join(outdir, apk_name)

        info_msg(f"Assembling {apk_name}")

        with open(apk_path, "wb") as f:
            if sig_gz:
                f.write(sig_gz)
            f.write(ctrl_gz)
            f.write(data_gz)

        apk_size = os.path.getsize(apk_path)
        signed = "yes" if sig_gz else "no"

        info_msg(f"Done!  {apk_path}  ({apk_size} bytes)")
        print()
        print(f"  Package : {args.name}")
        print(f"  Version : {args.version}-{args.release}")
        print(f"  Arch    : {args.arch}")
        print(f"  Signed  : {signed}")
        print()
        print(f"Install with:  apk add --allow-untrusted {apk_path}")

    finally:
        shutil.rmtree(work, ignore_errors=True)


def info_msg(msg: str) -> None:
    print(f"==> {msg}", file=sys.stderr)


if __name__ == "__main__":
    main()
